# https://github.com/Azure/aad-pod-identity/blob/b3ee1d07209f26c47a96abf3ba20749932763de6/website/content/en/docs/Concepts/azureidentity.md

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: podmi-caf-rover-platform-level0
spec:
    type: 0
    resourceID: ${resource_id}
    clientID: ${client_id}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: podmi-gitlab-runner-binding
spec:
    azureIdentity: podmi-caf-rover-platform-level0
    selector: podmi-caf-rover-platform-level0

